version: '3.9'
name: 'dl4se'

services:

  dl4se-db:
    container_name: dl4se-db
    image: postgres:15.7-alpine
    volumes:
      - data:/var/lib/postgresql/data
    networks: [ default ]
    environment:
      TZ: UTC
      POSTGRES_DB: dl4se
      POSTGRES_USER: dl4se_admin
      POSTGRES_PASSWORD: Lugano2023
    restart: always
    healthcheck:
      test: pg_isready -U dl4se_admin -d dl4se
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  dl4se-liquibase:
    container_name: dl4se-liquibase
    image: liquibase/liquibase:4.28.0-alpine
    environment:
      TZ: UTC
    command: >
      --username=dl4se_admin
      --password=Lugano2023
      --url=jdbc:postgresql://dl4se-db:5432/dl4se
      --changeLogFile=changelog.xml
      update
    volumes:
      - ../liquibase/changelog.xml:/liquibase/changelog.xml
      - ../liquibase/scripts/:/liquibase/scripts/
    networks: [ default ]
    depends_on:
      dl4se-db:
        condition: service_healthy

  dl4se-c